# Generated by Django 4.2.2 on 2023-06-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='owner',
            new_name='user',
        ),
    ]
